begin;
create extension if not exists pgtap with schema extensions;
select plan(27);
select has_table('private', 'product_unit_operations', 'private product-unit replay registry exists');
select col_is_pk('private', 'product_unit_operations', array['organization_id', 'operation_id'], 'operation identity is tenant-scoped');
select has_trigger('public', 'product_units', 'product_units_protect_identity', 'unit identity protection is enforced below the API');
select ok(pg_get_functiondef('private.protect_product_unit_identity()'::regprocedure) like '%The base unit cannot be deleted.%', 'base rows cannot be deleted');
select ok(pg_get_functiondef('private.protect_product_unit_identity()'::regprocedure) like '%The base unit code and conversion factor are immutable.%', 'base code and factor cannot change');
select ok(pg_get_functiondef('private.protect_product_unit_identity()'::regprocedure) like '%new.is_base is distinct from old.is_base%', 'base identity cannot be toggled');
select has_function('public', 'create_product_unit', array['uuid','uuid','text','text','numeric','boolean','boolean','uuid'], 'canonical create RPC exists');
select has_function('public', 'update_product_unit', array['uuid','uuid','text','text','numeric','boolean','boolean','uuid'], 'canonical update RPC exists');
select has_function('public', 'delete_product_unit', array['uuid','uuid','uuid'], 'canonical delete RPC exists');
select ok(pg_get_functiondef('public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%products.manage%', 'create enforces products.manage');
select ok(pg_get_functiondef('public.update_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%products.manage%', 'update enforces products.manage');
select ok(pg_get_functiondef('public.delete_product_unit(uuid,uuid,uuid)'::regprocedure) like '%products.manage%', 'delete enforces products.manage');
select ok(pg_get_functiondef('public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%lower(btrim(target_unit_code))%', 'create normalizes unit codes');
select ok(pg_get_functiondef('public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%pg_advisory_xact_lock%', 'create serializes competing normalized codes');
select ok(pg_get_functiondef('private.claim_product_unit_operation(uuid,uuid,text,jsonb,uuid)'::regprocedure) like '%existing.normalized_payload <> target_payload%', 'operation replay rejects payload conflicts');
select ok(pg_get_functiondef('private.claim_product_unit_operation(uuid,uuid,text,jsonb,uuid)'::regprocedure) like '%return existing.result_unit_id%', 'exact operation replay returns original result');
select ok(pg_get_functiondef('public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%PRODUCT_UNIT_CREATED%', 'create writes audit evidence');
select ok(pg_get_functiondef('public.update_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) like '%PRODUCT_UNIT_UPDATED%', 'update writes old/new audit evidence');
select ok(pg_get_functiondef('public.delete_product_unit(uuid,uuid,uuid)'::regprocedure) like '%PRODUCT_UNIT_DELETED%', 'delete writes old-value audit evidence');
select ok(pg_get_functiondef('public.update_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)'::regprocedure) not like '%purchase_order_lines%', 'unit edits never rewrite PO snapshots');
select ok(pg_get_functiondef('public.delete_product_unit(uuid,uuid,uuid)'::regprocedure) not like '%goods_receipt_lines%', 'unit deletion never rewrites receipt snapshots');
select ok(has_table_privilege('authenticated', 'public.product_units', 'select'), 'authenticated readers retain unit lookup access');
select ok(not has_table_privilege('authenticated', 'public.product_units', 'insert'), 'direct authenticated inserts are revoked');
select ok(not has_table_privilege('authenticated', 'public.product_units', 'update'), 'direct authenticated updates are revoked');
select ok(not has_table_privilege('authenticated', 'public.product_units', 'delete'), 'direct authenticated deletes are revoked');
select ok(has_function_privilege('authenticated', 'public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)', 'execute'), 'authenticated callers can use canonical create');
select ok(not has_function_privilege('anon', 'public.create_product_unit(uuid,uuid,text,text,numeric,boolean,boolean,uuid)', 'execute'), 'anonymous callers cannot mutate units');
select * from finish();
rollback;
