begin;
create extension if not exists pgtap with schema extensions;
select plan(17);
select has_column('public','pos_device_sync_telemetry','crash_count','aggregate crash count exists');
select has_column('public','pos_device_sync_telemetry','api_average_latency_ms','aggregate API latency exists');
select has_column('public','pos_device_sync_telemetry','api_failure_count','aggregate API failures exists');
select has_column('public','pos_device_sync_telemetry','sync_average_latency_ms','aggregate sync latency exists');
select has_column('public','pos_device_sync_telemetry','local_database_health','local DB health exists');
select has_column('public','pos_device_sync_telemetry','local_schema_version','local schema version exists');
select ok(to_regprocedure('public.report_pos_device_sync_telemetry(uuid,uuid,uuid,uuid,uuid,text,text,text,timestamptz,bigint,bigint,integer,integer,integer,timestamptz,bigint,timestamptz,timestamptz,integer,integer,integer,integer,integer,text,integer)') is not null,'expanded RPC exists');
select ok(not has_table_privilege('authenticated','public.pos_device_sync_telemetry','insert'),'authenticated cannot insert directly');
select ok(not has_table_privilege('authenticated','public.pos_device_sync_telemetry','update'),'authenticated cannot update directly');
insert into auth.users (id,email,raw_user_meta_data) values ('f2611111-1111-4111-8111-111111111111','phase26-owner@tindio.test','{"full_name":"Phase 26 Owner"}'::jsonb);
create temporary table phase26_context (organization_id uuid not null, store_id uuid not null, register_id uuid not null, employee_id uuid);
grant select,insert,update on phase26_context to authenticated;
set local role authenticated;
set local request.jwt.claim.sub = 'f2611111-1111-4111-8111-111111111111';
with bootstrap as (select * from public.bootstrap_organization('Phase 26 Observability','Phase 26 Store','Phase 26 Register')) insert into phase26_context (organization_id,store_id,register_id) select organization_id,store_id,register_id from bootstrap;
update phase26_context context set employee_id = employee.id from public.employees employee where employee.organization_id = context.organization_id and employee.profile_id = 'f2611111-1111-4111-8111-111111111111';
select ok((select private.has_permission(organization_id,'devices.manage') from phase26_context),'owner can manage devices');
select lives_ok(format($$select public.register_pos_device(%L,%L,%L,'f2622222-2222-4222-8222-222222222222','Phase 26 Terminal','android-test',repeat('a',64))$$,(select organization_id from phase26_context),(select store_id from phase26_context),(select register_id from phase26_context)),'owner can register terminal');
select lives_ok(format($$select public.report_pos_device_sync_telemetry(%L,'f2622222-2222-4222-8222-222222222222',%L,%L,%L,'Phase 26 Owner','CLOUD_ONLINE','android-test',now(),12,12,3,1,2,null,4,now()-interval '2 days',now()-interval '1 hour',120,900,2,800,5000,'HEALTHY',7)$$,(select organization_id from phase26_context),(select store_id from phase26_context),(select register_id from phase26_context),(select employee_id from phase26_context)),'terminal reports aggregates');
select is((select crash_count from public.pos_device_sync_telemetry where device_id='f2622222-2222-4222-8222-222222222222'),4::bigint,'crash count persists');
select is((select api_average_latency_ms from public.pos_device_sync_telemetry where device_id='f2622222-2222-4222-8222-222222222222'),120,'API latency persists');
select is((select sync_average_latency_ms from public.pos_device_sync_telemetry where device_id='f2622222-2222-4222-8222-222222222222'),800,'sync latency persists');
select is((select local_database_health from public.pos_device_sync_telemetry where device_id='f2622222-2222-4222-8222-222222222222'),'HEALTHY','local DB health persists');
select is((select local_schema_version from public.pos_device_sync_telemetry where device_id='f2622222-2222-4222-8222-222222222222'),7,'local schema version persists');
rollback;
