"use client";

import { Plus } from "lucide-react";
import { type FormEvent, useState, useTransition } from "react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { createDiningOptionAction, createDiscountAction, createModifierGroupAction, createTaxRateAction, createTicketTemplateAction } from "@/features/advanced-sales/actions";
import type { OrganizationFeatureSettings } from "@/features/business-profile/business-features";

const field = "h-9 rounded-lg border border-input bg-background px-3 text-sm";
export function AdvancedSalesManager({ products, canManage, diningOptions, ticketTemplates, features }: { products: Array<{ id: string; name: string }>; canManage: boolean; diningOptions: Array<{ id: string; name: string }>; ticketTemplates: Array<{ id: string; label: string; note: string | null; diningOptionId: string | null }>; features: Pick<OrganizationFeatureSettings, "dining" | "modifiers" | "open_tickets"> }) {
  if (!canManage) return <Card><CardContent className="py-6 text-sm text-muted-foreground">You can view advanced sales settings, but product-management access is required to change them.</CardContent></Card>;
  return <div className="grid gap-5 xl:grid-cols-2"><DiscountForm /><TaxForm />{features.dining ? <DiningForm /> : null}{features.open_tickets ? <TicketTemplateForm diningOptions={features.dining ? diningOptions : []} templates={ticketTemplates} /> : null}{features.modifiers ? <ModifierForm products={products} /> : null}</div>;
}
function Message({ text }: { text: string | null }) { return text ? <p aria-live="polite" className="text-sm text-muted-foreground">{text}</p> : null; }
function DiscountForm() { const [name,setName]=useState(""); const [type,setType]=useState("percentage"); const [value,setValue]=useState(""); const [message,setMessage]=useState<string|null>(null); const [pending,start]=useTransition(); const submit=(e:FormEvent)=>{e.preventDefault();start(async()=>{const r=await createDiscountAction({name,type,value});setMessage(r.message);if(r.ok){setName("");setValue("")}})}; return <Card><CardHeader><CardTitle>Discounts</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><Input placeholder="Senior discount" value={name} onChange={e=>setName(e.target.value)} /><div className="grid grid-cols-2 gap-3"><select className={field} value={type} onChange={e=>setType(e.target.value)}><option value="percentage">Percentage</option><option value="fixed_amount">Fixed amount</option></select><Input inputMode="decimal" placeholder={type === "percentage" ? "10" : "100.00"} value={value} onChange={e=>setValue(e.target.value)} /></div><Button disabled={pending} type="submit"><Plus />Add discount</Button><Message text={message}/></form></CardContent></Card>; }
function TaxForm() { const [name,setName]=useState(""); const [rate,setRate]=useState(""); const [inclusive,setInclusive]=useState(true); const [isDefault,setDefault]=useState(true); const [message,setMessage]=useState<string|null>(null); const [pending,start]=useTransition(); const submit=(e:FormEvent)=>{e.preventDefault();start(async()=>{const r=await createTaxRateAction({name,rate,inclusive,isDefault});setMessage(r.message);if(r.ok){setName("");setRate("")}})}; return <Card><CardHeader><CardTitle>Taxes</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><div className="grid grid-cols-2 gap-3"><Input placeholder="VAT" value={name} onChange={e=>setName(e.target.value)}/><Input inputMode="decimal" placeholder="12" value={rate} onChange={e=>setRate(e.target.value)}/></div><label className="text-sm"><input className="mr-2" type="checkbox" checked={inclusive} onChange={e=>setInclusive(e.target.checked)}/>Included in product prices</label><label className="text-sm"><input className="mr-2" type="checkbox" checked={isDefault} onChange={e=>setDefault(e.target.checked)}/>Use as default</label><Button disabled={pending} type="submit"><Plus />Add tax rate</Button><Message text={message}/></form></CardContent></Card>; }
function DiningForm() { const [name,setName]=useState(""); const [isDefault,setDefault]=useState(false); const [message,setMessage]=useState<string|null>(null); const [pending,start]=useTransition(); const submit=(e:FormEvent)=>{e.preventDefault();start(async()=>{const r=await createDiningOptionAction({name,isDefault});setMessage(r.message);if(r.ok)setName("")})}; return <Card><CardHeader><CardTitle>Dining options</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><Input placeholder="Dine in, Takeaway, Delivery" value={name} onChange={e=>setName(e.target.value)}/><label className="text-sm"><input className="mr-2" type="checkbox" checked={isDefault} onChange={e=>setDefault(e.target.checked)}/>Use as default</label><Button disabled={pending} type="submit"><Plus />Add dining option</Button><Message text={message}/></form></CardContent></Card>; }
function TicketTemplateForm({diningOptions,templates}:{diningOptions:Array<{id:string;name:string}>;templates:Array<{id:string;label:string;note:string|null;diningOptionId:string|null}>}) { const [label,setLabel]=useState(""); const [note,setNote]=useState(""); const [diningOptionId,setDiningOptionId]=useState(""); const [message,setMessage]=useState<string|null>(null); const [pending,start]=useTransition(); const submit=(e:FormEvent)=>{e.preventDefault();start(async()=>{const r=await createTicketTemplateAction({label,note,diningOptionId:diningOptionId||null});setMessage(r.message);if(r.ok){setLabel("");setNote("");setDiningOptionId("")}})}; return <Card><CardHeader><CardTitle>Ticket templates</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><Input placeholder="Table 1" value={label} onChange={e=>setLabel(e.target.value)}/><textarea className="min-h-20 rounded-lg border border-input bg-background px-3 py-2 text-sm" maxLength={500} placeholder="Optional order note" value={note} onChange={e=>setNote(e.target.value)}/><select className={field} value={diningOptionId} onChange={e=>setDiningOptionId(e.target.value)}><option value="">No dining option</option>{diningOptions.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select><Button disabled={pending} type="submit"><Plus/>Add ticket template</Button><Message text={message}/>{templates.length? <ul className="grid gap-1 border-t pt-3 text-sm text-muted-foreground">{templates.map(template=><li key={template.id}><span className="font-medium text-foreground">{template.label}</span>{template.note?` — ${template.note}`:""}</li>)}</ul>:null}</form></CardContent></Card>; }
function ModifierForm({products}:{products:Array<{id:string;name:string}>}) { const [name,setName]=useState("");const [min,setMin]=useState("0");const [max,setMax]=useState("1");const [options,setOptions]=useState([{name:"",price:"0.00"}]);const [ids,setIds]=useState<string[]>([]);const [message,setMessage]=useState<string|null>(null);const [pending,start]=useTransition();const submit=(e:FormEvent)=>{e.preventDefault();start(async()=>{const r=await createModifierGroupAction({name,min:Number(min),max:Number(max),options,productIds:ids});setMessage(r.message);if(r.ok){setName("");setOptions([{name:"",price:"0.00"}]);setIds([])}})};return <Card><CardHeader><CardTitle>Modifiers</CardTitle></CardHeader><CardContent><form className="grid gap-3" onSubmit={submit}><Input placeholder="Milk choice" value={name} onChange={e=>setName(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Input type="number" min="0" value={min} onChange={e=>setMin(e.target.value)}/><Input type="number" min="1" value={max} onChange={e=>setMax(e.target.value)}/></div>{options.map((option,index)=><div className="grid grid-cols-[1fr_7rem] gap-2" key={index}><Input placeholder="Option name" value={option.name} onChange={e=>setOptions(current=>current.map((item,i)=>i===index?{...item,name:e.target.value}:item))}/><Input inputMode="decimal" value={option.price} onChange={e=>setOptions(current=>current.map((item,i)=>i===index?{...item,price:e.target.value}:item))}/></div>)}<Button onClick={()=>setOptions(current=>[...current,{name:"",price:"0.00"}])} type="button" variant="outline"><Plus/>Add option</Button><fieldset><legend className="text-sm font-medium">Products using this group</legend><div className="mt-2 max-h-28 overflow-auto text-sm">{products.map(product=><label className="mr-4 inline-flex gap-1" key={product.id}><input type="checkbox" checked={ids.includes(product.id)} onChange={()=>setIds(current=>current.includes(product.id)?current.filter(id=>id!==product.id):[...current,product.id])}/>{product.name}</label>)}</div></fieldset><Button disabled={pending} type="submit"><Plus/>Create modifier group</Button><Message text={message}/></form></CardContent></Card>; }
