import type { PosBootstrapV2CoreResponse } from "../../../../src/contracts/pos";
import { getTindioDatabase } from "./database";

export async function saveBusinessContextSnapshot(core: PosBootstrapV2CoreResponse["core"]) {
  const capturedAt = new Date().toISOString();
  await (await getTindioDatabase()).runAsync("INSERT INTO business_context_snapshots (organization_id,profile_id,employee_id,organization_json,employee_json,available_organizations_json,role_names_json,permissions_json,store_ids_json,stores_json,registers_json,features_json,active_shift_json,captured_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(organization_id) DO UPDATE SET profile_id=excluded.profile_id,employee_id=excluded.employee_id,organization_json=excluded.organization_json,employee_json=excluded.employee_json,available_organizations_json=excluded.available_organizations_json,role_names_json=excluded.role_names_json,permissions_json=excluded.permissions_json,store_ids_json=excluded.store_ids_json,stores_json=excluded.stores_json,registers_json=excluded.registers_json,features_json=excluded.features_json,active_shift_json=excluded.active_shift_json,captured_at=excluded.captured_at", core.organization.id, core.profileId, core.employee.id, JSON.stringify(core.organization), JSON.stringify(core.employee), JSON.stringify(core.availableOrganizations), JSON.stringify(core.roleNames), JSON.stringify(core.permissions), JSON.stringify(core.storeIds), JSON.stringify(core.stores), JSON.stringify(core.registers), JSON.stringify(core.features), core.activeShift ? JSON.stringify(core.activeShift) : null, capturedAt);
  return capturedAt;
}
export async function hasBusinessContextSnapshot(organizationId: string) { const row = await (await getTindioDatabase()).getFirstAsync<{ found: number }>("SELECT 1 AS found FROM business_context_snapshots WHERE organization_id = ?", organizationId); return row?.found === 1; }
export async function getBusinessContextSnapshot(organizationId: string): Promise<CachedBusinessContext | null> { const row = await (await getTindioDatabase()).getFirstAsync<Record<string, string | null>>("SELECT * FROM business_context_snapshots WHERE organization_id = ?", organizationId); if (!row) return null; try { return { organizationId, capturedAt: row.captured_at!, core: { profileId: row.profile_id!, organization: JSON.parse(row.organization_json!), employee: JSON.parse(row.employee_json!), availableOrganizations: JSON.parse(row.available_organizations_json!), roleNames: JSON.parse(row.role_names_json!), permissions: JSON.parse(row.permissions_json!), storeIds: JSON.parse(row.store_ids_json!), stores: JSON.parse(row.stores_json!), registers: JSON.parse(row.registers_json!), features: JSON.parse(row.features_json!), activeShift: row.active_shift_json ? JSON.parse(row.active_shift_json) : null } }; } catch { return null; } }
export type CachedBusinessContext = { organizationId: string; core: PosBootstrapV2CoreResponse["core"]; capturedAt: string };
