import * as SQLite from "expo-sqlite";
import { LOCAL_MIGRATIONS, TINDIO_DATABASE_NAME, TINDIO_LOCAL_SCHEMA_VERSION } from "./schema";
let databasePromise: Promise<SQLite.SQLiteDatabase> | null = null;
async function openDatabase() { const database = await SQLite.openDatabaseAsync(TINDIO_DATABASE_NAME); await database.execAsync("PRAGMA journal_mode = WAL; PRAGMA foreign_keys = ON; PRAGMA busy_timeout = 5000; PRAGMA synchronous = NORMAL;"); let current = (await database.getFirstAsync<{ user_version: number }>("PRAGMA user_version"))?.user_version ?? 0; for (const migration of LOCAL_MIGRATIONS) if (migration.version > current) { await database.withExclusiveTransactionAsync(async (transaction) => { await transaction.execAsync(migration.sql); await transaction.execAsync(`PRAGMA user_version = ${migration.version}`); await transaction.runAsync("INSERT INTO local_metadata (key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at", "schema_version", String(migration.version), new Date().toISOString()); }); current = migration.version; } if (current !== TINDIO_LOCAL_SCHEMA_VERSION) throw new Error(`Unexpected local schema version ${current}.`); return database; }
export const getTindioDatabase = () => databasePromise ??= openDatabase();
export async function closeTindioDatabase() { if (databasePromise) { (await databasePromise).closeAsync(); databasePromise = null; } }
export async function getLocalSchemaVersion() { return (await getTindioDatabase()).getFirstAsync<{ user_version: number }>("PRAGMA user_version").then((row) => row?.user_version ?? 0); }
export async function writeLocalMetadata(key: string, value: string) { await (await getTindioDatabase()).runAsync("INSERT INTO local_metadata (key,value,updated_at) VALUES (?,?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at", key, value, new Date().toISOString()); }
export async function readLocalMetadata(key: string) { return (await getTindioDatabase()).getFirstAsync<{ value: string; updated_at: string }>("SELECT value,updated_at FROM local_metadata WHERE key = ?", key); }
