import { getTindioDatabase } from "./database";

export type SyncCursorState = { organizationId: string; deviceId: string; storeId: string; pullCursor: number; initialized: boolean; lastPushAt: string | null; lastPullAt: string | null; lastReconcileAt: string | null; lastError: string | null };
type Row = { organization_id: string; device_id: string; store_id: string; pull_cursor: number; initialized: number; last_push_at: string | null; last_pull_at: string | null; last_reconcile_at: string | null; last_error: string | null };
const toState = (row: Row): SyncCursorState => ({ organizationId: row.organization_id, deviceId: row.device_id, storeId: row.store_id, pullCursor: row.pull_cursor, initialized: row.initialized === 1, lastPushAt: row.last_push_at, lastPullAt: row.last_pull_at, lastReconcileAt: row.last_reconcile_at, lastError: row.last_error });
async function ensure(organizationId: string, deviceId: string, storeId: string) { const database = await getTindioDatabase(); await database.runAsync("INSERT INTO sync_cursors (organization_id,device_id,store_id) VALUES (?,?,?) ON CONFLICT(organization_id,device_id,store_id) DO NOTHING", organizationId, deviceId, storeId); return database; }
export async function getSyncCursor(organizationId: string, deviceId: string, storeId: string) { const database = await ensure(organizationId, deviceId, storeId); const row = await database.getFirstAsync<Row>("SELECT * FROM sync_cursors WHERE organization_id=? AND device_id=? AND store_id=?", organizationId, deviceId, storeId); return row ? toState(row) : null; }
export async function initializeSyncCursor(organizationId: string, deviceId: string, storeId: string, revision: number) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET pull_cursor=MAX(pull_cursor,?),initialized=1,last_error=NULL WHERE organization_id=? AND device_id=? AND store_id=?", revision, organizationId, deviceId, storeId); return getSyncCursor(organizationId, deviceId, storeId); }
export async function advanceSyncCursor(organizationId: string, deviceId: string, storeId: string, revision: number) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET pull_cursor=MAX(pull_cursor,?),last_pull_at=?,last_error=NULL WHERE organization_id=? AND device_id=? AND store_id=?", revision, new Date().toISOString(), organizationId, deviceId, storeId); return getSyncCursor(organizationId, deviceId, storeId); }
export async function markSyncPush(organizationId: string, deviceId: string, storeId: string) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET last_push_at=?,last_error=NULL WHERE organization_id=? AND device_id=? AND store_id=?", new Date().toISOString(), organizationId, deviceId, storeId); }
export async function markSyncPull(organizationId: string, deviceId: string, storeId: string) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET last_pull_at=?,last_error=NULL WHERE organization_id=? AND device_id=? AND store_id=?", new Date().toISOString(), organizationId, deviceId, storeId); }
export async function markReconcile(organizationId: string, deviceId: string, storeId: string) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET last_reconcile_at=?,last_error=NULL WHERE organization_id=? AND device_id=? AND store_id=?", new Date().toISOString(), organizationId, deviceId, storeId); }
export async function recordSyncError(organizationId: string, deviceId: string, storeId: string, error: string) { const database = await ensure(organizationId, deviceId, storeId); await database.runAsync("UPDATE sync_cursors SET last_error=? WHERE organization_id=? AND device_id=? AND store_id=?", error.slice(0, 500), organizationId, deviceId, storeId); }
