-- Canonical global permission catalogue.
--
-- The baseline intentionally contains schema only. These rows are immutable
-- reference data required by bootstrap and role-permission triggers, and were
-- previously introduced piecemeal by the archived historical migrations.
begin;

insert into public.permissions (code, name, category, description)
values
  ('approvals.authorize', 'Authorize manager approvals', 'Security', 'Approve a requested operation with a secure manager PIN.'),
  ('approvals.bypass', 'Bypass approval rules', 'Security', 'Perform a restricted operation without a second approver.'),
  ('approvals.manage', 'Manage approval rules', 'Security', 'Configure organization approval rules.'),
  ('approvals.request', 'Request manager approval', 'Security', 'Request a scoped approval for a restricted operation.'),
  ('attendance.use', 'Use attendance clock', 'Attendance', 'Clock authorized employees in and out from an assigned store terminal.'),
  ('audit.view', 'View audit log', 'Security', 'View immutable security and approval audit records.'),
  ('cash_drawer.open', 'Open cash drawer', 'POS', 'Record an authorized cash-drawer opening.'),
  ('cash.pay_in', 'Record pay-ins', 'Register', 'Record cash added to an open shift.'),
  ('cash.pay_out', 'Record pay-outs', 'Register', 'Record cash removed from an open shift.'),
  ('customers.manage', 'Manage customers', 'Customers', 'Create and maintain customer profiles.'),
  ('dashboard.view', 'View dashboard', 'Management', 'View the Back Office dashboard.'),
  ('devices.manage', 'Manage devices', 'Management', 'Manage registered TINDIO devices when device management is enabled.'),
  ('discounts.apply', 'Apply discounts', 'Sales', 'Apply permitted item or order discounts.'),
  ('employees.manage', 'Manage employees', 'Team', 'Manage employees and access assignments.'),
  ('inventory.adjust', 'Adjust inventory', 'Inventory', 'Create an inventory adjustment.'),
  ('inventory.adjust.create', 'Create inventory adjustments', 'Inventory', 'Prepare an authorized inventory adjustment.'),
  ('inventory.adjust.post', 'Post inventory adjustments', 'Inventory', 'Post an authorized inventory adjustment to the immutable stock ledger.'),
  ('inventory.count', 'Perform counts', 'Inventory', 'Complete an inventory count.'),
  ('inventory.count.create', 'Create inventory counts', 'Inventory', 'Create and prepare an inventory count.'),
  ('inventory.count.finalize', 'Finalize inventory counts', 'Inventory', 'Submit, post, or cancel an authorized inventory count.'),
  ('inventory.manage', 'Manage inventory', 'Inventory', 'Perform authorized stock operations.'),
  ('inventory.purchase_orders', 'Manage purchase orders', 'Inventory', 'Create and maintain purchase orders.'),
  ('inventory.receive', 'Receive inventory', 'Inventory', 'Receive a purchase order.'),
  ('inventory.suppliers', 'Manage suppliers', 'Inventory', 'Create and maintain suppliers.'),
  ('inventory.transfer.create', 'Create transfer requests', 'Inventory', 'Create an authorized request for stock to move between stores.'),
  ('inventory.transfer.receive', 'Receive stock transfers', 'Inventory', 'Record authorized stock-transfer receipts at an assigned destination store.'),
  ('inventory.transfer.send', 'Send stock transfers', 'Inventory', 'Approve, pick, and dispatch stock from an authorized source store.'),
  ('inventory.transfers', 'Manage transfers', 'Inventory', 'Transfer stock between assigned stores.'),
  ('inventory.valuation.view', 'View inventory valuation', 'Inventory', 'View inventory valuation and cost-sensitive stock values.'),
  ('inventory.view', 'View inventory', 'Inventory', 'View stock projections and movement history.'),
  ('kitchen.manage', 'Manage kitchen orders', 'Kitchen', 'Advance kitchen orders through preparation and completion.'),
  ('kitchen.view', 'View kitchen display', 'Kitchen', 'View active kitchen orders for assigned stores.'),
  ('organization.archive', 'Archive organization', 'Management', 'Suspend, resume, or safely archive an organization after an export.'),
  ('organization.export', 'Export organization data', 'Management', 'Create a rate-limited, tenant-scoped business data export.'),
  ('organization.lifecycle', 'Manage organization lifecycle', 'Management', 'Request or cancel an organization archival workflow.'),
  ('organization.manage', 'Manage organization', 'Management', 'Manage organization-level business settings.'),
  ('payments.accept', 'Accept payments', 'POS', 'Complete an eligible POS payment.'),
  ('pos.access', 'Access POS', 'POS', 'Open the point-of-sale workspace.'),
  ('pos.edit_quantity', 'Edit cart quantities', 'POS', 'Change a temporary POS cart quantity.'),
  ('pos.remove_item', 'Remove cart items', 'POS', 'Remove a temporary POS cart quantity.'),
  ('prices.override', 'Override prices', 'Sales', 'Override the configured selling price during a sale.'),
  ('products.manage', 'Manage products', 'Catalog', 'Create and maintain products and categories.'),
  ('products.view_cost', 'View product cost', 'Catalog', 'View product acquisition cost and margins.'),
  ('purchasing.po.create', 'Create purchase orders', 'Purchasing', 'Create and maintain authorized purchase orders.'),
  ('purchasing.receive', 'Receive purchase orders', 'Purchasing', 'Receive authorized supplier deliveries.'),
  ('purchasing.return', 'Return stock to suppliers', 'Purchasing', 'Record authorized supplier returns.'),
  ('purchasing.suppliers.manage', 'Manage suppliers', 'Purchasing', 'Create and maintain supplier records.'),
  ('purchasing.view', 'View purchasing', 'Purchasing', 'View authorized suppliers, purchase orders, and receiving records.'),
  ('receipts.reprint', 'Reprint receipts', 'Sales', 'Reprint completed transaction receipts.'),
  ('receipts.view', 'View receipts', 'Sales', 'View completed receipt history and details.'),
  ('recovery.manage', 'Record recovery verification', 'Management', 'Record an owner-authorized backup or recovery drill after it has been tested.'),
  ('recovery.view', 'View backup and recovery readiness', 'Management', 'View tenant export, recovery-drill, and retention readiness.'),
  ('registers.manage', 'Manage registers', 'Management', 'Create and maintain POS registers.'),
  ('reports.view', 'View reports', 'Reports', 'View authorized business reports.'),
  ('roles.manage', 'Manage roles', 'Team', 'Create roles and assign permissions.'),
  ('sales.create', 'Create sales', 'Sales', 'Create and complete point-of-sale transactions.'),
  ('sales.refund', 'Refund sales', 'Sales', 'Create full or partial refunds against completed sales.'),
  ('settings.manage', 'Manage settings', 'Management', 'Manage business configuration.'),
  ('shifts.close', 'Close shifts', 'Register', 'Count and close a register shift.'),
  ('shifts.force_close', 'Force close shifts', 'Register', 'Force-close a shift after explicit manager approval.'),
  ('shifts.open', 'Open shifts', 'Register', 'Open a register shift.'),
  ('shifts.view_expected_cash', 'View expected cash', 'Register', 'View calculated expected drawer cash.'),
  ('shifts.view_history', 'View shift history', 'Register', 'View closed register shift history.'),
  ('stores.manage', 'Manage stores', 'Management', 'Create and maintain stores.'),
  ('tickets.manage', 'Manage open tickets', 'POS', 'Create, update, complete, or cancel open tickets.')
on conflict (code) do update
set name = excluded.name,
    category = excluded.category,
    description = excluded.description;

commit;
