import { spawnSync } from "node:child_process";
import process from "node:process";

function quoteWindowsArgument(value) {
  const text = String(value);
  if (!/[\s"&|<>^]/.test(text)) return text;
  return `"${text.replace(/(\\*)"/g, "$1$1\\\"").replace(/(\\+)$/g, "$1$1")}"`;
}

/**
 * Runs a repository command without Node's `shell: true` mode.
 *
 * On Windows, pnpm is normally exposed as `pnpm.cmd`. Node cannot reliably
 * spawn that batch shim directly with `shell: false` (notably from Git Bash),
 * so invoke it through the Windows command processor explicitly. Arguments are
 * generated by repository code rather than user input.
 */
export function runCommand(command, args = [], options = {}) {
  const cwd = options.cwd ?? process.cwd();
  const env = options.env ?? process.env;
  const capture = options.capture ?? false;
  const encoding = options.encoding ?? "utf8";
  const stdio = capture ? ["ignore", "pipe", "pipe"] : "inherit";

  let executable = command;
  let executableArgs = args;

  if (command === "node") {
    executable = process.execPath;
  } else if (process.platform === "win32" && command === "pnpm") {
    executable = process.env.ComSpec || "cmd.exe";
    const commandLine = ["pnpm", ...args].map(quoteWindowsArgument).join(" ");
    executableArgs = ["/d", "/s", "/c", commandLine];
  }

  return spawnSync(executable, executableArgs, {
    cwd,
    env,
    encoding,
    stdio,
    shell: false,
  });
}
