import "server-only";

import { checkoutSubmissionSchema } from "@/features/checkout/checkout-schema";
import { completeCheckout } from "@/features/checkout/checkout-service";
import type { CheckoutSaleActionResult, CheckoutSequenceInfo } from "@/features/checkout/checkout-types";
import { posDeviceRequestHeaders } from "@/features/devices/device-schema";
import type { BusinessContext } from "@/lib/auth/dal";
import { createBusinessContextClient } from "@/lib/supabase/context-client";

type RpcClient = { rpc: (name: string, args: Record<string, unknown>) => Promise<{ data: Array<Record<string, unknown>> | null; error: { message?: string } | null }> };
const sequenceStatuses = new Set<CheckoutSequenceInfo["status"]>(["ACCEPTED", "REPLAY", "GAP", "DUPLICATE_SEQUENCE", "OUT_OF_ORDER", "IDEMPOTENCY_SEQUENCE_MISMATCH"]);
const sequenceInfo = (value: Record<string, unknown>, deviceSequence: number): CheckoutSequenceInfo | null => { const status=value.status, serverCheckpoint=Number(value.server_checkpoint), expectedSequence=Number(value.expected_sequence); return typeof status==="string"&&sequenceStatuses.has(status as CheckoutSequenceInfo["status"])&&Number.isSafeInteger(serverCheckpoint)&&Number.isSafeInteger(expectedSequence)?{deviceSequence,serverCheckpoint,expectedSequence,status:status as CheckoutSequenceInfo["status"]}:null; };
const sequenceFailure = (sync: CheckoutSequenceInfo): CheckoutSaleActionResult => ({ ok:false,retryable:false,failureCode:sync.status==="GAP"?"SEQUENCE_GAP":sync.status==="OUT_OF_ORDER"?"SEQUENCE_OUT_OF_ORDER":"SEQUENCE_CONFLICT",sync,message:"This saved sale cannot be applied until its device sequence is reconciled." });

async function reserve(context: BusinessContext,input: unknown): Promise<{kind:"none"}|{kind:"rejected";result:CheckoutSaleActionResult;status:number}|{kind:"retryable"}|{kind:"reserved";sync:CheckoutSequenceInfo}> { const parsed=checkoutSubmissionSchema.safeParse(input); if(!parsed.success) return {kind:"none"}; const offline=parsed.data.offline; if(!offline||offline.deviceSequence===undefined)return{kind:"none"}; if(!parsed.data.device||offline.deviceId!==parsed.data.device.deviceId)return{kind:"rejected",status:409,result:{ok:false,retryable:false,failureCode:"SEQUENCE_CONFLICT",message:"The saved sale device identity is invalid."}}; const database=await createBusinessContextClient(context,{headers:posDeviceRequestHeaders(parsed.data.device)}) as unknown as RpcClient; const validation=await database.rpc("validate_pos_device",{target_organization_id:context.organization.id,target_device_id:parsed.data.device.deviceId,target_secret:parsed.data.device.secret,target_app_version:parsed.data.device.appVersion}); const device=validation.data?.[0]; if(validation.error||!device||String(device.device_id)!==parsed.data.device.deviceId||String(device.store_id)!==parsed.data.checkout.storeId||String(device.register_id)!==parsed.data.checkout.registerId)return{kind:"rejected",status:403,result:{ok:false,retryable:false,failureCode:"DEVICE_REVOKED",message:"This POS device is not active for the saved sale terminal."}}; const reservation=await database.rpc("reserve_pos_device_sequence",{target_organization_id:context.organization.id,target_device_id:parsed.data.device.deviceId,target_store_id:parsed.data.checkout.storeId,target_register_id:parsed.data.checkout.registerId,target_device_sequence:offline.deviceSequence,target_idempotency_key:parsed.data.checkout.idempotencyKey,target_local_receipt_reference:offline.localReceiptReference}); const sync=reservation.data?.[0]?sequenceInfo(reservation.data[0],offline.deviceSequence):null; if(reservation.error||!sync)return{kind:"retryable"}; return sync.status==="ACCEPTED"||sync.status==="REPLAY"?{kind:"reserved",sync}:{kind:"rejected",status:409,result:sequenceFailure(sync)}; }
async function finalize(context: BusinessContext,input: unknown,sync: CheckoutSequenceInfo,result: CheckoutSaleActionResult){if(!result.ok&&result.retryable)return sync;const parsed=checkoutSubmissionSchema.parse(input);const database=await createBusinessContextClient(context,{headers:posDeviceRequestHeaders(parsed.device)}) as unknown as RpcClient;const finalized=await database.rpc("finalize_pos_device_sequence",{target_organization_id:context.organization.id,target_device_id:parsed.device!.deviceId,target_device_sequence:sync.deviceSequence,target_idempotency_key:parsed.checkout.idempotencyKey,target_final_state:result.ok?"APPLIED":"CONFLICT"});const checkpoint=Number(finalized.data?.[0]?.server_checkpoint);return finalized.error||!Number.isSafeInteger(checkpoint)?null:{...sync,serverCheckpoint:checkpoint,expectedSequence:checkpoint+1};}
async function record(context: BusinessContext,input: unknown,result: CheckoutSaleActionResult){const parsed=checkoutSubmissionSchema.safeParse(input);if(!parsed.success||!parsed.data.offline||(!result.ok&&result.retryable))return;const offline=parsed.data.offline;const supabase=await createBusinessContextClient(context,{headers:posDeviceRequestHeaders(parsed.data.device)});const conflictType=!result.ok&&["SEQUENCE_GAP","SEQUENCE_CONFLICT","SEQUENCE_OUT_OF_ORDER"].includes(result.failureCode??"")?"PERMISSION_CHANGED":!result.ok?result.failureCode??"PERMISSION_CHANGED":null;await supabase.rpc("record_offline_sync_event",{target_organization_id:context.organization.id,target_store_id:parsed.data.checkout.storeId,target_register_id:parsed.data.checkout.registerId,target_shift_id:offline.shiftId,target_device_id:offline.deviceId as never,target_idempotency_key:parsed.data.checkout.idempotencyKey,target_local_receipt_reference:offline.localReceiptReference,target_local_created_at:offline.createdAt,target_state:result.ok?"SYNCED":"CONFLICT",target_conflict_type:conflictType as never,target_failure_message:(result.ok?null:result.message) as never,target_official_receipt_number:(result.ok?result.data.receiptNumber:null) as never});}
export async function processPosV2OfflineCheckout(context: BusinessContext,input: unknown): Promise<{status:number;result:CheckoutSaleActionResult}>{const reservation=await reserve(context,input);if(reservation.kind==="rejected"){await record(context,input,reservation.result);return{status:reservation.status,result:reservation.result};}if(reservation.kind==="retryable")return{status:503,result:{ok:false,message:"TINDIO could not reserve this device sequence. The saved sale will remain queued.",retryable:true}};const result=await completeCheckout(context,input,{guardOfflineTotal:true});const sync=reservation.kind==="reserved"?await finalize(context,input,reservation.sync,result):undefined;if(reservation.kind==="reserved"&&!sync)return{status:503,result:{ok:false,message:"TINDIO accepted the sale but could not finalize its sequence checkpoint. Retry this same saved sale.",retryable:true}};const sequenced=sync?{...result,sync}:result;await record(context,input,sequenced);return{status:sequenced.ok?200:sequenced.retryable?503:409,result:sequenced};}
